// Official NSC subject list (all 11 languages as Home Language and First
// Additional Language, plus every standard NSC subject). Shared by the
// learner marks form (EnterMarks) and the admin Quick Check so both offer
// exactly the same subjects.
export const NSC_SUBJECTS = [
  "Afrikaans Home Language",
  "Afrikaans First Additional Language",
  "English Home Language",
  "English First Additional Language",
  "isiNdebele Home Language",
  "isiNdebele First Additional Language",
  "isiXhosa Home Language",
  "isiXhosa First Additional Language",
  "isiZulu Home Language",
  "isiZulu First Additional Language",
  "Sepedi Home Language",
  "Sepedi First Additional Language",
  "Sesotho Home Language",
  "Sesotho First Additional Language",
  "Setswana Home Language",
  "Setswana First Additional Language",
  "Siswati Home Language",
  "Siswati First Additional Language",
  "South African Sign Language Home Language",
  "South African Sign Language First Additional Language",
  "Tshivenda Home Language",
  "Tshivenda First Additional Language",
  "Xitsonga Home Language",
  "Xitsonga First Additional Language",
  "Accounting",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Business Studies",
  "CAT (Computer Applications Technology)",
  "Civil Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics and Design",
  "Geography",
  "History",
  "Hospitality Studies",
  "IT (Information Technology)",
  "Life Orientation",
  "Life Sciences",
  "Marine Sciences",
  "Maritime Economics",
  "Mathematical Literacy",
  "Mathematics",
  "Mechanical Technology",
  "Music",
  "Physical Sciences",
  "Religion Studies",
  "Technical Mathematics",
  "Technical Science",
  "Tourism",
  "Visual Arts",
];

// Starting rows for a fresh marks form.
export const DEFAULT_SUBJECT_ROWS = [
  { subject: "English Home Language", mark: "" },
  { subject: "Mathematics", mark: "" },
  { subject: "Life Orientation", mark: "" },
  { subject: "Accounting", mark: "" },
  { subject: "Business Studies", mark: "" },
  { subject: "Geography", mark: "" },
  { subject: "Physical Sciences", mark: "" },
];
